 # This workflow will perform archinaut analysis on the project and generate a report
 # on the metrics analyzed

 # This is the name of the workflow
name: Archinaut analysis
on: [push]
jobs:
  archinaut-analysis:
    runs-on: ubuntu-latest
    name: A job to perform archinaut analysis of source code
    steps:
      # Check out our repository
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      # Do the Archinaut analysis
      - name: Archinaut analysis
        id: archinaut
        uses: hdmsantander/archinaut-action@main
        with:
          init date: '2020-01-01'
          min cochanges: 0
          scc cloc: 450
          scc complexity: 70
          scc loc: 410
          arch revisions: 30
          arch dependent partners: 50
          arch depends on partners: 70
          arch total dependencies: 70
          arch cochange partners: 20
          arch churn: 500
                
      # Store the Archinaut artifact
      - name: Archive Archinaut results as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: archinaut
          path: archinaut.csv
      
      # Create the report
      - name: Generate report using Archinaut XML output
        uses: EnricoMi/publish-unit-test-result-action@v1.7
        if: always()
        with:
         check_name: 'Archinaut analysis results'
         report_individual_runs: true
         github_token: ${{ secrets.GITHUB_TOKEN }}
         files: archinaut.xml
