 # This workflow will perform archinaut analysis on the project and generate a report
 # on the metrics analyzed

 # This is the name of the workflow
name: Archinaut analysis
on: [push]
jobs:
  archinaut-analysis:
    runs-on: ubuntu-latest
    name: A job to perform archinaut analysis of source code
    steps:
      # Check out our repository
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      # Do the Archinaut analysis
      - name: Archinaut analysis
        id: archinaut
        uses: hdmsantander/archinaut-action@main
        with:
          init date: '2020-01-01'
          min cochanges: 0
      
      # Store the Archinaut artifact
      - name: Archive Archinaut results as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: archinaut
          path: archinaut.csv
      
      # Create the report
      - name: Generate report using Archinaut XML output
        uses: EnricoMi/publish-unit-test-result-action@v1.7
        if: always()
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: archinaut.xml
