# This workflow will deploy to GitHub packages repository each
# time there's a new release on the project

# Name of this workflow
name: Publish package to GitHub Packages

# This workflow is triggered upon the creation of a new release
on:
  release:
    types: [created]

# The jobs on this workflow
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish package
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
