# This workflow will perform SCC Analysis of the source code

# This is the name of the workflow
name: SCC analysis
on: [push]
jobs:
  code_analysis:
    runs-on: ubuntu-latest
    name: A job to perform analysis of source code using SCC
    steps:
      
      # Check out our repository
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      # SCC Analysis
      - name: Perform SCC analysis of code
        id: scc
        uses: hdmsantander/scc-docker-action@3.0
        with:
          args: ${{ env.workspace }} src --by-file --ci -i java -o scc.json -f json

      # Store the SCC artifact
      - name: Archive SCC results as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: scc
          path: scc.json
  json_manipulation:
    runs-on: ubuntu-latest
    name: A job to manipulate the JSONs generated in the code analysis step
    needs: [code_analysis]
    steps:
      
      # Download the SCC artifact
      - name: Download SCC results
        uses: actions/download-artifact@v2
        with:
          name: scc
      
      # JSON Transformation for SCC
      - name: Transform SCC results
        id: json-scc
        uses: hdmsantander/npm-commit-date-ifier-action@v1.0
        with:
          json: ${{ env.workspace }} scc.json
          
      # Store the SCC artifact
      - name: Archive SCC results as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: scc
          path: scc.json